# Generated by Django 2.0 on 2017-12-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
