# Generated by Django 2.0 on 2017-12-26 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20171223_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='updated_at',
        ),
    ]
